config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('es_manager.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

es_manager/urls.py
from django.urls import path
from . import views

app_name = 'es_manager'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('es_list/', views.EntrySheetListView.as_view(), name='es_list'),
    path('es_detail/<int:pk>/', views.EntrySheetDetailView.as_view(), name='es_detail'),
    path('es_create/', views.EntrySheetCreateView.as_view(), name='es_create'),
    path('es_update/<int:pk>/', views.EntrySheetUpdateView.as_view(), name='es_update'),
    path('es_delete/<int:pk>/', views.EntrySheetDeleteView.as_view(), name='es_delete'),
]

es_manager/models.py
from accounts.models import CustomUser
from django.db import models
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(
        verbose_name='カテゴリー名',
        max_length=127,

    )
    def __str__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(
        verbose_name='企業名',
        max_length=127,
    )

    deadline = models.DateTimeField(
        verbose_name='提出期限',
        default=timezone.now
    )

    def __str__(self):
        return self.name

    def deadline_mdHM(self):
        return self.deadline.strftime('%月%d日%H:%M')

class EntrySheet(models.Model):
    user = models.ForeignKey(
        CustomUser,
        verbose_name='ユーザー',
        on_delete=models.PROTECT,
    )
    title = models.CharField(
        verbose_name='タイトル',
        max_length=255,
    )
    content = models.TextField(
        verbose_name='本文',
        blank=True,
        null=True,
    )
    content_max_length = models.SmallIntegerField(
        verbose_name='最大文字数',
        blank=True,
        null=True,
    )
    content_min_length = models.SmallIntegerField(
        verbose_name='最小文字数',
        blank=True,
        null=True,
    )
    photo1 = models.ImageField(
        verbose_name='写真1',
        blank=True,
        null=True,
    )
    photo2 = models.ImageField(
        verbose_name='写真2',
        blank=True,
        null=True,
    )
    photo3 = models.ImageField(
        verbose_name='写真3',
        blank=True,
        null=True,
    )
    is_public = models.BooleanField(
        default=False
    )
    created_at = models.DateTimeField(
        verbose_name='作成日時',
        auto_now=True,
    )
    updated_at = models.DateTimeField(
        verbose_name='更新日時',
        auto_now=True,
    )
    categories = models.ManyToManyField(
        Category,
        verbose_name='カテゴリー',
        blank=True,
    )
    companies = models.ManyToManyField(
        Company,
        verbose_name='企業',
        blank=True,
    )


    def __str__(self):
        return self.title

es_manager/forms.py
from django import forms
from django.core.mail import EmailMessage
from .models import EntrySheet, Category, Company


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {0}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'admin@example.com'
        to_list = [
            'test@example.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()


class EntrySheetCreateForm(forms.ModelForm):
    class Meta:
        model = EntrySheet
        fields = ('title',
                  'content', 'content_max_length', 'content_min_length',
                  'categories', 'companies',
                  'photo1', 'photo2', 'photo3',
                  )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

es_manager/views.py
from django.views.generic import TemplateView
from django.views.generic import FormView
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.urls import reverse_lazy
from django.contrib import messages

from .models import EntrySheet, Category, Company

from .forms import InquiryForm, EntrySheetCreateForm

import logging

logger = logging.getLogger(__name__)

class IndexView(TemplateView):
    template_name = 'index.html'

class AboutView(TemplateView):
    template_name = 'about.html'


class InquiryView(FormView):
    template_name = 'inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('es_manager:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


class EntrySheetListView(LoginRequiredMixin, ListView):
    model = EntrySheet
    context_object_name = 'es_list'
    template_name = 'es_manager/es_list.html'
    paginate_by = 5

    def get_queryset(self):
        entry_sheets = EntrySheet.objects.filter(user_id=self.request.user).order_by('-created_at')
        return entry_sheets

class EntrySheetDetailView(LoginRequiredMixin, DetailView):
    model = EntrySheet
    template_name = 'es_manager/es_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = self.object.categories.all()
        context['company_list'] = self.object.companies.all()
        return context

class EntrySheetCreateView(LoginRequiredMixin, CreateView):
    model = EntrySheet
    template_name = 'es_manager/es_create.html'
    form_class = EntrySheetCreateForm
    success_url = reverse_lazy('es_manager:es_list')

    def form_valid(self, form):
        es = form.save(commit=False)
        es.user = self.request.user
        es.save()
        messages.success(self.request, 'エントリーシートを作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "エントリーシートの作成に失敗しました。")
        return super().form_invalid(form)

class EntrySheetUpdateView(LoginRequiredMixin, UpdateView):
    model = EntrySheet
    template_name = 'es_manager/es_update.html'
    form_class = EntrySheetCreateForm

    def get_success_url(self):
        return reverse_lazy('es_manager:es_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'エントリーシートを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, 'エントリーシートの更新に失敗しました。')
        return super().form_invalid(form)

class EntrySheetDeleteView(LoginRequiredMixin, DeleteView):
    model = EntrySheet
    template_name = 'es_manager/es_delete.html'
    success_url = reverse_lazy('es_manager:es_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'エントリーシートを削除しました。')
        return super().delete(request, *args, **kwargs)

templates/es_manager/es_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}新規作成|Hunt Assist〜ES編集・管理〜{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="col-9 float-left">
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table">
          {{ form.as_table }}
        </table>
        <button class="btn btn-primary" type="submit">作成</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/es_manager/es_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除|Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <form method="POST">
      {% csrf_token %}
      <p>本当に削除しますか？</p>
      <button class="btn btn-primary mt-5" type="submit">削除</button>
      <a class="btn btn-secondary mt-5 ml-2" href="{% url 'es_manager:es_detail' object.pk %}">キャンセル</a>
    </form>
  </div>
</div>
{% endblock %}

templates/es_manager/es_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Hunt Assist〜ES編集・管理〜{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container">
  <div class="row">
    <div class="col-2">
      <strong>タイトル</strong>
    </div>
    <div class="col-9">
      {{ object.title }}
    </div>
  </div>
  <hr>

  <div class="row">
    <div class="col-2">
      <strong>本文</strong>
    </div>
    <div class="col-9">
      {{ object.content|linebreaksbr }}
      <p>({{ object.content|length }}文字)</p>
    </div>
  </div>

  <div class="row">
    <div class="col-2">
      <strong>制限</strong>
    </div>
    <div class="col-9">
      {% if object.content_min_length %}
      {{ object.content_min_length }}字以上
      {% endif %}
      {% if object.content_max_length %}
      {{ object.content_max_length }}字以内
      {% endif %}
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-2">
      <strong>カテゴリー</strong>
    </div>
    <div class="col-9">
      {% for category in category_list %}
      <p> {{ category }}</p>
      {% endfor %}
    </div>
  </div>

  <hr>

    <div class="row">
    <div class="col-2">
      <strong>企業</strong>
    </div>
    <div class="col-9">
      {% for company in company_list %}
      <p> {{ company }} 提出期限({{ company.deadline_mdHM }})</p>
      {% endfor %}
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-2">
      {% if object.photo1 %}
      <img src="{{ object.photo1.url }}" width="200" height="200"/>
      {% endif %}
    </div>
    <div class="col-2">
      {% if object.photo2 %}
      <img src="{{ object.photo2.url }}" width="200" height="200"/>
      {% endif %}
    </div>
    <div class="col-2">
      {% if object.photo3 %}
      <img src="{{ object.photo3.url }}" width="200" height="200"/>
      {% endif %}
    </div>
  </div>


  <div class="row">
    <div class="col-2">
      <strong>作成日時</strong>
    </div>
    <div class="col-9">
      {{ object.created_at }}
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-2">
      <strong>更新日時</strong>
    </div>
    <div class="col-9">
      {{ object.updated_at }}
    </div>
  </div>
  <a class="btn btn-success mt-5 mb-3" href="{% url 'es_manager:es_update' object.pk %}">編集</a>
  <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'es_manager:es_delete' object.pk %}">削除</a>
</div>
{% endblock %}

templates/es_manager/es_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Hunt Assist〜ES編集・管理〜{% endblock %}

{%block active_es_list %}active{% endblock %}


{% block contents %}
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <div class="clearfix">
        <a class="btn btn-primary float-right" href="{% url 'es_manager:es_create' %}"">新規作成</a>
      </div>
      {% for es in es_list %}
      <div class="post_preview">
        <a href="{% url 'es_manager:es_detail' es.pk %}">
          <h2 class="post-title">
            {{ es.title }}
          </h2>
          <h3 class="post-subtitle">
            {{ es.content|truncatechars:20 }}
          </h3>
        </a>
        <p class="post-meta">{{ es.created_at }}</p>
      </div>
      <hr>
      {% empty %}
      <p>日記がありません。</p>
      {% endfor %}

      <!-- ページネーション処理 -->

      {% if is_paginated %}
      <ul class="pagination">
        <!-- 前ページのリンク -->
        {% if page_obj.previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
        {% endif %}

        <!-- ページ数表示 -->
        {% for page_num in page_obj.paginator.page_range %}
        {% if page_obj.number == page_num %}
        <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
        {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
        {% endif %}
        {% endfor %}

        <!-- 次のページのリンク -->
        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        {% endif %}
      </ul>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/es_manager/es_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集|Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <table class="table">
        {{ form.as_table }}
      </table>
      <button class="btn btn-primary" type="submit">更新</button>
      <a class="btn btn-secondary ml-2" href="{% url 'es_manager:es_detail' object.pk %}">キャンセル</a>
    </form>
  </div>
</div>
{% endblock %}