config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('es_manager.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

es_manager/urls.py
from django.urls import path
from . import views

app_name = 'es_manager'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about/', views.AboutView.as_view(), name="about"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('es_list/', views.EntrySheetListView.as_view(), name='es_list'),
    path('es_detail/<int:pk>/', views.EntrySheetDetailView.as_view(), name='es_detail'),
    path('es_create/', views.EntrySheetCreateView.as_view(), name='es_create'),
    path('es_update/<int:pk>/', views.EntrySheetUpdateView.as_view(), name='es_update'),
    path('es_delete/<int:pk>/', views.EntrySheetDeleteView.as_view(), name='es_delete'),
]

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Hunt Assist〜EntrySheet編集・管理〜{% endblock %}

{% block active_about %}active{% endblock %}

{% block header %}{% endblock %}

{% block contents %}
<div class="text-center">
  <img class="img-fluid" src="{% static '/img/icons/linkedin_banner_image_2.png' %}">
</div>
{% endblock %}

templates/base.html
{% load static %}

<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- My style CSS -->
  <link href="{% static 'css/mystyle.css' %}" rel="stylesheet">

</head>

<body id="page-top">

<!-- Header -->
<header>
  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-sm navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4"
            aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand text-success" href="{% url 'es_manager:index' %}">Hunt Assist</a>
    <p class="text-white mt-3">〜ES編集・管理アプリケーション〜</p>
    <p class="text-white ml-5 mt-3">ユーザー：{{ user.email|default:'-' }}</p>
    <div class="collapse navbar-collapse justify-content-end">
      <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item {% block active_es_list %}{% endblock %}">
          <a class="nav-link" href="{% url 'es_manager:es_list' %}">ES List</a>
        </li>
        {% endif %}
        <li class="nav-item {% block active_about %}{% endblock %}">
          <a class="nav-link" href="{% url 'es_manager:about' %}">About</a>
        </li>
        <li class="nav-item {% block active_inquiry %}{% endblock %}">
          <a class="nav-link" href="{% url 'es_manager:inquiry' %}">Inquiry</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item {% block active_logout %}{% endblock %}">
          <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item {% block active_signup %}{% endblock %}">
          <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
        </li>
        <li class="nav-item {% block active_login %}{% endblock %}">
          <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% block header %}{% endblock %}
</header>

{% if messages %}
<div class="container">
  <div class="row">
    <div class="my-div-style w-100">
      <ul class="messages" style="list-style: none;">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
          {{ message }}
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>
{% endif %}

<!-- messagesがない時はnavbarの分だけcontentsを下げる -->
<div {% if not messages %} class="my-div-style" {% endif %}>
  {% block contents %}{% endblock %}
</div>

<!-- Footer -->
<footer class="footer bg-dark mt-auto py-5">
  <span class="text-muted">Copyright &copy; Hunt Assist 2021</span>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Hunt Assist〜ES編集・管理〜{% endblock %}

{% block header %}{% endblock %}

{% block contents %}
<div class="text-center">
  <img class="img-fluid" src="{% static '/img/icons/linkedin_banner_image_2.png' %}">
</div>
<div class="row">
  <div class="col-6"><img class="img-fluid" src="{% static '/img/bg-callout.jpg' %}"></div>
  <div class="col-6 mh-100 py-5 bg-info bg-circle">
    <h1>ESを編集できる</h1>
    <br>
    <h3>就職活動でたくさん作るES(エントリーシート)を<br>このアプリで作ろう</h3>
    <h3>文字数カウンタ付きで文字数を確認しながら編集できる</h3>
  </div>
</div>
<div class="row">
  <div class="col-6 mh-100 py-5 bg-primary">
    <h1>ESを保存して管理できる</h1>
    <br>
    <h3>就職活動でたくさん作るES(エントリーシート)を<br>このアプリで保存！</h3>
    <h3>タグ付け機能で検索して再利用できる</h3>
  </div>
  <div class="col-6"><img class="img-fluid" src="{% static '/img/bg-masthead.jpg' %}"></div>
</div>

{% endblock %}

templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ|Hunt Assist〜ES編集・管理〜{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}

<div class="container">
  <div class="row">
    <h1>お問い合わせ</h1>
  </div>
  <form method="post">
    {% csrf_token %}

    {{ form.non_field_errors }}

    {% for field in form %}
    <div class="form-group row">
      <label for="{{ field.id_for_label }}" class="col-4 col-form-label">
        <strong class="right">{{ field.label_tag }}</strong>
      </label>
      <div class="col-8">
        {{ field }}
        {{ field.errors }}
      </div>
    </div>
    {% endfor %}

    <div class="offset-sm-4 col-sm-1">
      <button class="btn btn-primary" type="submit">送信</button>
    </div>
  </form>
</div>
{% endblock %}